# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import requests
import io
from PIL import Image
from PyQt5.QtWidgets import QGraphicsScene
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import Qt, QThread, pyqtSignal


class WorkerThread(QThread):
    image_loaded = pyqtSignal(bytes)

    def __init__(self, api_url, headers, data):
        super(WorkerThread, self).__init__()
        self.api_url = api_url
        self.headers = headers
        self.data = data

    def run(self):
        try:
            response = requests.post(self.api_url, headers=self.headers, json=self.data)
            print("Here")
            if response.status_code == 200:
                image_bytes = response.content
                self.image_loaded.emit(image_bytes)
            else:
                print("Error fetching image:", response.status_code)
        except Exception as e:
            print("Exception during API request:", str(e))


class Ui_Dialog(object):
    def getimg(self, text):
        self.worker_thread = WorkerThread(self.api, self.header, data={"inputs": text})

        self.worker_thread.image_loaded.connect(self.display_image)
        self.worker_thread.start()

    def display_image(self, image_bytes):
        pixmap = QPixmap()
        pixmap.loadFromData(image_bytes)

        scene = QGraphicsScene()
        scene.addPixmap(pixmap)
        pg = "im_pg" + str(self.pg_disp.currentIndex())
        print(pg)
        graphics_view = getattr(self, pg, None)

        if graphics_view:
            graphics_view.setScene(scene)
        else:
            print(f"Attribute {pg} not found.")

    def query(self, payload):
        response = requests.post(self.API_URL, headers=self.headers, json=payload)
        return response.content

    def openwindow(self, index):
        new_page_index = (index + 1) % self.pg_disp.count()
        self.pg_disp.setCurrentIndex(new_page_index)

    def setupUi(self, Dialog):
        
        Dialog.setObjectName("Dialog")
        Dialog.resize(1125, 735)
        Dialog.setMinimumSize(QtCore.QSize(1125, 735))
        Dialog.setMaximumSize(QtCore.QSize(1125, 735))
        Dialog.setWindowIcon(QIcon('dashtoon.png'))
        Dialog.setStyleSheet("")
        self.pg_disp = QtWidgets.QTabWidget(Dialog)
        self.pg_disp.setEnabled(True)
        self.pg_disp.setGeometry(QtCore.QRect(0, 0, 1120, 731))
        self.pg_disp.setMinimumSize(QtCore.QSize(1120, 731))
        self.pg_disp.setMaximumSize(QtCore.QSize(1120, 731))
        self.pg_disp.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pg_disp.setAutoFillBackground(False)
        self.pg_disp.setTabEnabled(0,False)
        self.pg_disp.setStyleSheet(
            "background-color: #E0E0E0; /* Light grey color */\n" "\n" ""
        )
        self.pg_disp.setObjectName("pg_disp")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.main_pg_but = QtWidgets.QPushButton(
            self.tab_11, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.main_pg_but.setGeometry(QtCore.QRect(740, 20, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setItalic(True)
        self.main_pg_but.setFont(font)
        self.main_pg_but.setStyleSheet(
            "background-color: rgba(255, 255, 255, 220);\n" ""
        )
        self.main_pg_but.setObjectName("main_pg_but")
        self.label_3 = QtWidgets.QLabel(self.tab_11)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1111, 701))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("one-piece.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab_11)
        self.label.setGeometry(QtCore.QRect(157, 620, 471, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n" "")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_11)
        self.label_2.setGeometry(QtCore.QRect(10, 580, 141, 121))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 200);\n" "")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("dashtoon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3.raise_()
        self.main_pg_but.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pg_disp.addTab(self.tab_11, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.im_pg1 = QtWidgets.QGraphicsView(self.tab)
        self.im_pg1.setGeometry(QtCore.QRect(0, 0, 1120, 551))
        self.im_pg1.setObjectName("im_pg1")
        self.create_pg1 = QtWidgets.QPushButton(
            self.tab, clicked=lambda: self.getimg(self.inp_pg1.text())
        )
        self.create_pg1.setGeometry(QtCore.QRect(300, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.create_pg1.setFont(font)
        self.create_pg1.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.create_pg1.setObjectName("create_pg1")
        self.inp_pg1 = QtWidgets.QLineEdit(self.tab)
        self.inp_pg1.setGeometry(QtCore.QRect(10, 560, 1101, 50))
        self.inp_pg1.setMinimumSize(QtCore.QSize(1101, 41))
        self.inp_pg1.setMaximumSize(QtCore.QSize(1101, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.inp_pg1.setFont(font)
        self.inp_pg1.setStyleSheet(
            "background-color: rgb(170,200,200); /* Light grey color */\n" ""
        )
        self.inp_pg1.setText("")
        self.inp_pg1.setObjectName("inp_pg1")
        self.But_pg1 = QtWidgets.QPushButton(
            self.tab, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.But_pg1.setGeometry(QtCore.QRect(860, 630, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.But_pg1.setFont(font)
        self.But_pg1.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.But_pg1.setObjectName("But_pg1")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(120, 610, 71, 91))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("chichar.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(14, 616, 91, 81))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("pokemon.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(200, 610, 110, 91))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("pich.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(540, 620, 291, 81))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("ct1.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.pg_disp.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.im_pg2 = QtWidgets.QGraphicsView(self.tab_3)
        self.im_pg2.setGeometry(QtCore.QRect(0, 0, 1120, 551))
        self.im_pg2.setObjectName("im_pg2")
        self.inp_pg2 = QtWidgets.QLineEdit(self.tab_3)
        self.inp_pg2.setGeometry(QtCore.QRect(10, 560, 1101, 50))
        self.inp_pg2.setMinimumSize(QtCore.QSize(1101, 41))
        self.inp_pg2.setMaximumSize(QtCore.QSize(1101, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.inp_pg2.setFont(font)
        self.inp_pg2.setStyleSheet(
            "background-color: rgb(170,200,200); /* Light grey color */\n" ""
        )
        self.inp_pg2.setText("")
        self.inp_pg2.setObjectName("inp_pg2")
        self.create_pg2 = QtWidgets.QPushButton(
            self.tab_3, clicked=lambda: self.getimg(self.inp_pg2.text())
        )
        self.create_pg2.setGeometry(QtCore.QRect(300, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.create_pg2.setFont(font)
        self.create_pg2.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.create_pg2.setObjectName("create_pg2")
        self.But_pg2 = QtWidgets.QPushButton(
            self.tab_3, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.But_pg2.setGeometry(QtCore.QRect(860, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.But_pg2.setFont(font)
        self.But_pg2.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.But_pg2.setObjectName("But_pg2")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(550, 610, 271, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("shin.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(10, 620, 271, 81))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("ct.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.pg_disp.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.im_pg3 = QtWidgets.QGraphicsView(self.tab_4)
        self.im_pg3.setGeometry(QtCore.QRect(0, 0, 1120, 551))
        self.im_pg3.setObjectName("im_pg3")
        self.But_pg3 = QtWidgets.QPushButton(
            self.tab_4, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.But_pg3.setGeometry(QtCore.QRect(870, 630, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.But_pg3.setFont(font)
        self.But_pg3.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.But_pg3.setObjectName("But_pg3")
        self.inp_pg3 = QtWidgets.QLineEdit(self.tab_4)
        self.inp_pg3.setGeometry(QtCore.QRect(10, 561, 1101, 50))
        self.inp_pg3.setMinimumSize(QtCore.QSize(1101, 41))
        self.inp_pg3.setMaximumSize(QtCore.QSize(1101, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.inp_pg3.setFont(font)
        self.inp_pg3.setStyleSheet(
            "background-color: rgb(170,200,200); /* Light grey color */\n" ""
        )
        self.inp_pg3.setText("")
        self.inp_pg3.setObjectName("inp_pg3")
        self.create_pg3 = QtWidgets.QPushButton(
            self.tab_4, clicked=lambda: self.getimg(self.inp_pg3.text())
        )
        self.create_pg3.setGeometry(QtCore.QRect(300, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.create_pg3.setFont(font)
        self.create_pg3.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.create_pg3.setObjectName("create_pg3")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(550, 620, 271, 81))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("ct.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(10, 620, 281, 81))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("ct1.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.pg_disp.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.im_pg4 = QtWidgets.QGraphicsView(self.tab_5)
        self.im_pg4.setGeometry(QtCore.QRect(0, 0, 1120, 551))
        self.im_pg4.setObjectName("im_pg4")
        self.But_pg4 = QtWidgets.QPushButton(
            self.tab_5, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.But_pg4.setGeometry(QtCore.QRect(870, 629, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.But_pg4.setFont(font)
        self.But_pg4.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.But_pg4.setObjectName("But_pg4")
        self.inp_pg4 = QtWidgets.QLineEdit(self.tab_5)
        self.inp_pg4.setGeometry(QtCore.QRect(10, 560, 1101, 50))
        self.inp_pg4.setMinimumSize(QtCore.QSize(1101, 41))
        self.inp_pg4.setMaximumSize(QtCore.QSize(1101, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.inp_pg4.setFont(font)
        self.inp_pg4.setStyleSheet(
            "background-color: rgb(170,200,200); /* Light grey color */\n" ""
        )
        self.inp_pg4.setText("")
        self.inp_pg4.setObjectName("inp_pg4")
        self.create_pg4 = QtWidgets.QPushButton(
            self.tab_5, clicked=lambda: self.getimg(self.inp_pg4.text())
        )
        self.create_pg4.setGeometry(QtCore.QRect(300, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.create_pg4.setFont(font)
        self.create_pg4.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.create_pg4.setObjectName("create_pg4")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(550, 610, 271, 91))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("shin.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(126, 610, 71, 91))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("chichar.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(20, 616, 91, 81))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("pokemon.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(206, 610, 110, 91))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("pich.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.pg_disp.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.im_pg5 = QtWidgets.QGraphicsView(self.tab_6)
        self.im_pg5.setGeometry(QtCore.QRect(0, 0, 1120, 551))
        self.im_pg5.setObjectName("im_pg5")
        self.But_pg5 = QtWidgets.QPushButton(
            self.tab_6, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.But_pg5.setGeometry(QtCore.QRect(870, 630, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.But_pg5.setFont(font)
        self.But_pg5.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.But_pg5.setObjectName("But_pg5")
        self.inp_pg5 = QtWidgets.QLineEdit(self.tab_6)
        self.inp_pg5.setGeometry(QtCore.QRect(10, 560, 1101, 50))
        self.inp_pg5.setMinimumSize(QtCore.QSize(1101, 41))
        self.inp_pg5.setMaximumSize(QtCore.QSize(1101, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.inp_pg5.setFont(font)
        self.inp_pg5.setStyleSheet(
            "background-color: rgb(170,200,200); /* Light grey color */\n" ""
        )
        self.inp_pg5.setText("")
        self.inp_pg5.setObjectName("inp_pg5")
        self.create_pg5 = QtWidgets.QPushButton(
            self.tab_6, clicked=lambda: self.getimg(self.inp_pg5.text())
        )
        self.create_pg5.setGeometry(QtCore.QRect(300, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.create_pg5.setFont(font)
        self.create_pg5.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.create_pg5.setObjectName("create_pg5")
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(20, 620, 271, 81))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("ct.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(554, 615, 261, 81))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("th1.jpeg"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.pg_disp.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.im_pg6 = QtWidgets.QGraphicsView(self.tab_7)
        self.im_pg6.setGeometry(QtCore.QRect(0, 0, 1120, 551))
        self.im_pg6.setObjectName("im_pg6")
        self.But_pg6 = QtWidgets.QPushButton(
            self.tab_7, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.But_pg6.setGeometry(QtCore.QRect(870, 630, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.But_pg6.setFont(font)
        self.But_pg6.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.But_pg6.setObjectName("But_pg6")
        self.inp_pg6 = QtWidgets.QLineEdit(self.tab_7)
        self.inp_pg6.setGeometry(QtCore.QRect(10, 560, 1101, 50))
        self.inp_pg6.setMinimumSize(QtCore.QSize(1101, 41))
        self.inp_pg6.setMaximumSize(QtCore.QSize(1101, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.inp_pg6.setFont(font)
        self.inp_pg6.setStyleSheet(
            "background-color: rgb(170,200,200); /* Light grey color */\n" ""
        )
        self.inp_pg6.setText("")
        self.inp_pg6.setObjectName("inp_pg6")
        self.create_pg6 = QtWidgets.QPushButton(
            self.tab_7, clicked=lambda: self.getimg(self.inp_pg6.text())
        )
        self.create_pg6.setGeometry(QtCore.QRect(300, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.create_pg6.setFont(font)
        self.create_pg6.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.create_pg6.setObjectName("create_pg6")
        self.label_17 = QtWidgets.QLabel(self.tab_7)
        self.label_17.setGeometry(QtCore.QRect(110, 610, 71, 91))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("chichar.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_7)
        self.label_18.setGeometry(QtCore.QRect(4, 616, 91, 81))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("pokemon.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_7)
        self.label_19.setGeometry(QtCore.QRect(190, 610, 110, 91))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("pich.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_31 = QtWidgets.QLabel(self.tab_7)
        self.label_31.setGeometry(QtCore.QRect(540, 620, 291, 81))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("ct1.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.pg_disp.addTab(self.tab_7, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.im_pg7 = QtWidgets.QGraphicsView(self.tab_10)
        self.im_pg7.setGeometry(QtCore.QRect(0, 0, 1120, 551))
        self.im_pg7.setObjectName("im_pg7")
        self.But_pg7 = QtWidgets.QPushButton(
            self.tab_10, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.But_pg7.setGeometry(QtCore.QRect(870, 630, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.But_pg7.setFont(font)
        self.But_pg7.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.But_pg7.setObjectName("But_pg7")
        self.inp_pg7 = QtWidgets.QLineEdit(self.tab_10)
        self.inp_pg7.setGeometry(QtCore.QRect(10, 560, 1101, 50))
        self.inp_pg7.setMinimumSize(QtCore.QSize(1101, 41))
        self.inp_pg7.setMaximumSize(QtCore.QSize(1101, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.inp_pg7.setFont(font)
        self.inp_pg7.setStyleSheet(
            "background-color: rgb(170,200,200); /* Light grey color */\n" ""
        )
        self.inp_pg7.setText("")
        self.inp_pg7.setObjectName("inp_pg7")
        self.create_pg7 = QtWidgets.QPushButton(
            self.tab_10, clicked=lambda: self.getimg(self.inp_pg7.text())
        )
        self.create_pg7.setGeometry(QtCore.QRect(300, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.create_pg7.setFont(font)
        self.create_pg7.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.create_pg7.setObjectName("create_pg7")
        self.label_6 = QtWidgets.QLabel(self.tab_10)
        self.label_6.setGeometry(QtCore.QRect(550, 610, 271, 91))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("shin.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_26 = QtWidgets.QLabel(self.tab_10)
        self.label_26.setGeometry(QtCore.QRect(20, 620, 271, 81))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("ct.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.pg_disp.addTab(self.tab_10, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.im_pg8 = QtWidgets.QGraphicsView(self.tab_9)
        self.im_pg8.setGeometry(QtCore.QRect(0, 0, 1120, 551))
        self.im_pg8.setObjectName("im_pg8")
        self.But_pg8 = QtWidgets.QPushButton(
            self.tab_9, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.But_pg8.setGeometry(QtCore.QRect(870, 629, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.But_pg8.setFont(font)
        self.But_pg8.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.But_pg8.setObjectName("But_pg8")
        self.inp_pg8 = QtWidgets.QLineEdit(self.tab_9)
        self.inp_pg8.setGeometry(QtCore.QRect(10, 560, 1101, 50))
        self.inp_pg8.setMinimumSize(QtCore.QSize(1101, 41))
        self.inp_pg8.setMaximumSize(QtCore.QSize(1101, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.inp_pg8.setFont(font)
        self.inp_pg8.setStyleSheet(
            "background-color: rgb(170,200,200); /* Light grey color */\n" ""
        )
        self.inp_pg8.setText("")
        self.inp_pg8.setObjectName("inp_pg8")
        self.create_pg8 = QtWidgets.QPushButton(
            self.tab_9, clicked=lambda: self.getimg(self.inp_pg8.text())
        )
        self.create_pg8.setGeometry(QtCore.QRect(300, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.create_pg8.setFont(font)
        self.create_pg8.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.create_pg8.setObjectName("create_pg8")
        self.label_11 = QtWidgets.QLabel(self.tab_9)
        self.label_11.setGeometry(QtCore.QRect(110, 610, 71, 91))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("chichar.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_9)
        self.label_12.setGeometry(QtCore.QRect(4, 616, 91, 81))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("pokemon.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_9)
        self.label_13.setGeometry(QtCore.QRect(190, 610, 110, 91))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("pich.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_32 = QtWidgets.QLabel(self.tab_9)
        self.label_32.setGeometry(QtCore.QRect(540, 620, 291, 81))
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("ct1.png"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.pg_disp.addTab(self.tab_9, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.im_pg9 = QtWidgets.QGraphicsView(self.tab_8)
        self.im_pg9.setGeometry(QtCore.QRect(0, 0, 1120, 551))
        self.im_pg9.setObjectName("im_pg9")
        self.But_pg9 = QtWidgets.QPushButton(
            self.tab_8, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.But_pg9.setGeometry(QtCore.QRect(870, 629, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.But_pg9.setFont(font)
        self.But_pg9.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.But_pg9.setObjectName("But_pg9")
        self.inp_pg9 = QtWidgets.QLineEdit(self.tab_8)
        self.inp_pg9.setGeometry(QtCore.QRect(10, 560, 1101, 50))
        self.inp_pg9.setMinimumSize(QtCore.QSize(1101, 41))
        self.inp_pg9.setMaximumSize(QtCore.QSize(1101, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.inp_pg9.setFont(font)
        self.inp_pg9.setStyleSheet(
            "background-color: rgb(170,200,200); /* Light grey color */\n" ""
        )
        self.inp_pg9.setText("")
        self.inp_pg9.setObjectName("inp_pg9")
        self.create_pg9 = QtWidgets.QPushButton(
            self.tab_8, clicked=lambda: self.getimg(self.inp_pg9.text())
        )
        self.create_pg9.setGeometry(QtCore.QRect(300, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.create_pg9.setFont(font)
        self.create_pg9.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.create_pg9.setObjectName("create_pg9")
        self.label_27 = QtWidgets.QLabel(self.tab_8)
        self.label_27.setGeometry(QtCore.QRect(560, 620, 271, 81))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("ct.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_33 = QtWidgets.QLabel(self.tab_8)
        self.label_33.setGeometry(QtCore.QRect(10, 620, 281, 81))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("ct1.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.pg_disp.addTab(self.tab_8, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.im_pg10 = QtWidgets.QGraphicsView(self.tab_2)
        self.im_pg10.setGeometry(QtCore.QRect(0, 0, 1120, 551))
        self.im_pg10.setObjectName("im_pg10")
        self.But_pg10 = QtWidgets.QPushButton(
            self.tab_2, clicked=lambda: self.openwindow(self.pg_disp.currentIndex())
        )
        self.But_pg10.setGeometry(QtCore.QRect(870, 630, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.But_pg10.setFont(font)
        self.But_pg10.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.But_pg10.setObjectName("But_pg10")
        self.inp_pg10 = QtWidgets.QLineEdit(self.tab_2)
        self.inp_pg10.setGeometry(QtCore.QRect(10, 560, 1101, 50))
        self.inp_pg10.setMinimumSize(QtCore.QSize(1101, 41))
        self.inp_pg10.setMaximumSize(QtCore.QSize(1101, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.inp_pg10.setFont(font)
        self.inp_pg10.setStyleSheet(
            "background-color: rgb(170,200,200); /* Light grey color */\n" ""
        )
        self.inp_pg10.setText("")
        self.inp_pg10.setObjectName("inp_pg10")
        self.create_pg10 = QtWidgets.QPushButton(
            self.tab_2, clicked=lambda: self.getimg(self.inp_pg10.text())
        )
        self.create_pg10.setGeometry(QtCore.QRect(300, 630, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.create_pg10.setFont(font)
        self.create_pg10.setStyleSheet(
            "QPushButton{\n"
            "    background-color: rgba(170,200,200);\n"
            "} /* Light grey color */\n"
            "QPushButton:hover{\n"
            "    background:rgba(170,200,200,220);\n"
            "}\n"
            "QPushButton:pressed{\n"
            "    background:rgba(170,200,200,250);\n"
            "}\n"
            ""
        )
        self.create_pg10.setObjectName("create_pg10")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(550, 620, 271, 81))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("shin.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(14, 616, 91, 81))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("pokemon.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(120, 610, 71, 91))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("chichar.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(200, 610, 110, 91))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("pich.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.pg_disp.addTab(self.tab_2, "")
        self.api = "https://xdwvg9no7pefghrn.us-east-1.aws.endpoints.huggingface.cloud"
        self.header = {
            "Accept": "image/png",
            "Authorization": "Bearer VknySbLLTUjbxXAXCjyfaFIPwUTCeRXbFSOjwRiCxsxFyhbnGjSFalPKrpvvDAaPVzWEevPljilLVDBiTzfIbWFdxOkYJxnOPoHhkkVGzAknaOulWggusSFewzpqsNWM",
            "Content-Type": "application/json",
        }

        self.retranslateUi(Dialog)
        self.pg_disp.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "dAsHtOOn"))
        self.main_pg_but.setText(_translate("Dialog", "Let's Start"))
        self.label.setText(_translate("Dialog", "Welcome to DashTOOn"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab_11), _translate("Dialog", "Page")
        )
        self.create_pg1.setText(_translate("Dialog", "Create"))
        self.But_pg1.setText(_translate("Dialog", "Next Page"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab), _translate("Dialog", "Page1")
        )
        self.create_pg2.setText(_translate("Dialog", "Create"))
        self.But_pg2.setText(_translate("Dialog", "Next Page"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab_3), _translate("Dialog", "Page 2")
        )
        self.But_pg3.setText(_translate("Dialog", "Next Page"))
        self.create_pg3.setText(_translate("Dialog", "Create"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab_4), _translate("Dialog", "Page 3")
        )
        self.But_pg4.setText(_translate("Dialog", "Next Page"))
        self.create_pg4.setText(_translate("Dialog", "Create"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab_5), _translate("Dialog", "Page 4")
        )
        self.But_pg5.setText(_translate("Dialog", "Next Page"))
        self.create_pg5.setText(_translate("Dialog", "Create"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab_6), _translate("Dialog", "Page 5")
        )
        self.But_pg6.setText(_translate("Dialog", "Next Page"))
        self.create_pg6.setText(_translate("Dialog", "Create"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab_7), _translate("Dialog", "Page 6")
        )
        self.But_pg7.setText(_translate("Dialog", "Next Page"))
        self.create_pg7.setText(_translate("Dialog", "Create"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab_10), _translate("Dialog", "Page 7")
        )
        self.But_pg8.setText(_translate("Dialog", "Next Page"))
        self.create_pg8.setText(_translate("Dialog", "Create"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab_9), _translate("Dialog", "Page 8")
        )
        self.But_pg9.setText(_translate("Dialog", "Next Page"))
        self.create_pg9.setText(_translate("Dialog", "Create"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab_8), _translate("Dialog", "Page 9")
        )
        self.But_pg10.setText(_translate("Dialog", "Next Page"))
        self.create_pg10.setText(_translate("Dialog", "Create"))
        self.pg_disp.setTabText(
            self.pg_disp.indexOf(self.tab_2), _translate("Dialog", "Page 10")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
